name: Build Image
run-name: Build and Publish Docker Image
on:
  push:
    tags: ["v*"]
permissions: 
  packages: write
jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}